VERSION				?= 0.0

PACKAGE				= plsc
PACKAGE_BUGREPORT	= https://github.com/d0p1s4m4/PLSc/issues
PACKAGE_NAME		= PL/Stupid Compiler
PACKAGE_VERSION		= $(VERSION)
PACKAGE_STRING		= $(PACKAGE_NAME) $(PACKAGE_VERSION)
PACKAGE_TARNAME		= $(PACKAGE)
PACKAGE_URL			= https://github.com/d0p1s4m4/PLSc

PACKAGE_STR	= \"$(PACKAGE)\"
PACKAGE_BUGREPORT_STR = \"$(PACKAGE_BUGREPORT)\"
