.TH PLSC 1

.SH NAME
plsc \- PL/Stupid Compiler

.SH SYNOPSIS
\fBplsc\fR [\fIOPTION...\fR] [\fIFILE...\fR]

.SH DESCRIPTION

.SH BUGS
See <https://github.com/d0p1s4m4/PLSc/issues>

.SH EXAMPLES
.TP
Compile a file
plsc main.pls

.SH COPYRIGHT
Copyright \(co 2023 d0p1.
.br
License BSD-3-Clause: <https://directory.fsf.org/wiki/License:BSD-3-Clause>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
